version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - type: git
        url: https://github.com
        repo: PitiRR/microservices-demo
        patterns:
          - "v*"